# Taken from #209

FROM alpine AS base
ENV FOO=foo
RUN echo FOO=$FOO

FROM base AS devel
ENV BAR=bar
RUN echo FOO=$FOO BAR=$BAR

FROM devel AS devel2
RUN echo FOO=$FOO BAR=$BAR

FROM devel2 AS devel3
RUN echo FOO=$FOO BAR=$BAR
