FROM mirror.gcr.io/alpine
ARG SECRET
ARG UNUSED
ARG INHERITED=set
RUN echo "$SECRET"

FROM mirror.gcr.io/alpine
ARG FOO=test
ARG BAR=bartest
RUN echo "$FOO:$BAR"
RUN echo "$SECRET"

FROM 0
RUN echo "$SECRET"
