FROM centos:7
COPY archived.txt /archived/
COPY archived.tar /archived-tar/
COPY archived.tar.gz /archived-gz/
COPY archived.tar.bz2 /archived-bz2/
COPY archived.tar.xz /archived-xz/
COPY archived.txt archived.tar.xz archived.tar.bz2 /archived-mixed/
COPY archived.txt /archived.tar.xz ./archived.tar.bz2 /archived-mixed-path-variations/
