FROM centos:7
ADD archived.txt /archived/
ADD archived.tar /archived-tar/
ADD archived.tar.gz /archived-gz/
ADD archived.tar.bz2 /archived-bz2/
ADD archived.tar.xz /archived-xz/
ADD archived.txt archived.tar.xz archived.tar.bz2 /archived-mixed/
ADD archived.txt /archived.tar.xz ./archived.tar.bz2 /archived-mixed-path-variations/
